sudo: required
language: python
python:
- 3.7
services:
- docker
jobs:
  include:
  - stage: Deploy Docker Images to Docker Hub
    if: type != pull_request
    script:
    - "$TRAVIS_BUILD_DIR/distribute.sh"
env:
  global:
    - ADDON_NAME=presence-monitor
    - DOCKER_USERNAME=limych
    - secure: L7GOrphgZxfgUwCgJS6uTqXJAg6Rr1S89/fTguB+RnHU6WUbhNu/kXxY8HEGYUcg1icRHt4mpQQmUHYugtcNdZDqoXvkWbc00OuVQC4FEuISgmJaHgIATAi+r3WLXXsYfZWOLYMmQUrOZLPcFLe5yzUEt8Q81nIx/6Jz/atNdmtaRgHtPtNzST7YIAghrunoAwgUQ2UWL97CTE7LToIIZ7L5wZGeYsxEs6lF6WUqjAzU7w0Kata1z44kxi11D7XmIL8TjztuS2nZlZj2+SbPK1qCSPYk5G/6ahma9AKgjaeIq+0X7kW+O0UIc8NOluQFWgJ8CXS36meOCNfUWVk5YB+o4EMeUGXR8aUW0Iz/ZMJQg9HyThAG5Gs2NDLXRxET8UQ8yMnb6py59EGiZ30c8SoGrU8CzBGyKur4oSzlN6YBzYeNRG/43fj1HWCiaB+VEH9fI+EeSlEvlU9t3cpZQ1dgV67Ms5MwrLMtMtlclFrlHcn6m3hCVr0u9slI8rWokExiLgVSRxvMH5cKCIcyeN6ltybiZQs0W6kKEfX7ySekggPCjbxy3bSbiBY/5V0wESi4/uJu1dR8OVZ4E4YW9Y/GDPdJVBrGLeR1vOQzsmZJMS6M1ql+wjR1N7zCuhKrBFEBlRoZqbM/ohTrLueuKz2Kl1vmIGmiA/Np7mB9bwM=
